### ISSUE TITLE
Improve buffer heirarchy

### ISSUE THREAD

**Issue by ryzokuken** [khyperia/weechat-discord#25]
When running this, two things are very noticeable: The buffer list is flooded with entries and Every buffer has a huge name (`server name || chatroom name`). Instead, I wonder if there would be a way to make empty server buffers just like IRC server buffers, and if possible, 1 level under another empty buffer named "Discord". All chatrooms from that discord server would be inside the corresponding buffer, and you will not have to use those huge names. Plus, it would look a lot cleaner and organized, especially if you use indentation.

**Comment by ryzokuken** [comment]
@khyperia Hey! I'm sorry, but I don't understand why you closed this... Is this solved already? You didn't reference a PR to this issue. Perhaps you didn't find this relevant, although I personally feel this is important enough to bother you even though you must be busy and bring this to your notice. Whichever way, I think you should have explained the reason in a comment.

Thanks.

**Comment by khyperia** [comment]
Yes! Sorry, I thought the close message from the commit would be enough - `khyperia closed this in 873f4dd a day ago`, the commit message includes `Fixes #25`. I don't use a PR model for this project, I just push directly to master, since it's a small side-project with me as the only contributor.

It should now look like the below! Sorry again about the lack of communication there 😅

![buffers](https://user-images.githubusercontent.com/953151/28535480-68309d12-7059-11e7-9d52-888d25dde95f.png)

Note your suggestion of `1 level under another empty buffer named "Discord".` seems kind of difficult - I don't think `buflist` can do double-indentation (indentation is created by setting a buffer mode "this is a channel", and weechat's GUI recognizes that and indents it). Also, I still have a todo item, PMs have no "server buffer", so they're just kind of floating out there (kind of unfortunately visually associated with whatever channel list is above it). I'll try to get to that soon :)

**Comment by ryzokuken** [comment]
Oh, I must have missed the message, I am sorry. You did properly reference this issue then 😅 

No problem, this still looks super awesome. Thanks.

I do Rust on the side for some security stuff, maybe I will try to look into the codebase and help you out someday.

Thanks again for making this awesome software and listening to suggestions.
